FROM buildpack-deps:jammy-curl

LABEL org.opencontainers.image.source=https://github.com/kompiro/devcontainers
LABEL org.opencontainers.image.description="kompiro development base environment"
LABEL org.opencontainers.image.licenses=APLv2
